### ISSUE TITLE
Feedback on “ZFS on a FreeBSD Droplet” post

### ISSUE THREAD

**Issue by andrewtj** [2bithacker/2bithacker.github.io#1]
With your post I was able to get a FreeBSD on ZFS droplet up and running for a quick play - thank you!

A couple of nits:
- The path to `pkg-static` should be `/usr/local/sbin/pkg-static` rather than `/usr/local/bin/pkg-static`.
- Should the reference to setting up networking in `loader.conf` instead refer to `rc.conf`? (I'm new to FreeBSD so I might have this wrong.)

Cheers

**Comment by 2bithacker** [comment]
Yeah, I noticed the pkg-static path was wrong the last time I ran through the procedure myself a couple weeks ago. I'll be updating it soon for 10.3R and will make sure to fix the path then.

Normally network settings would be in `rc.conf` but for the mfsBSD boot the entire configuration is done through `loader.conf`, see https://github.com/mmatuska/mfsbsd/blob/master/conf/loader.conf.sample for reference.
