### ISSUE TITLE
Building mfsbsd-10.3 on 10.2 does not work

### ISSUE THREAD

**Issue by oholiab** [2bithacker/2bithacker.github.io#2]
I'm pretty certain it's because of pkg-static still being the older version, but it still produces the 10.2 versioned tarfile.

**Comment by oholiab** [comment]
(fwiw when I upgraded to 10.3 with freebsd-update and then repeated, it worked just fine)

**Comment by 2bithacker** [comment]
I'll have to take a look at the mfsbsd build scripts, it must be pulling in part of the host OS rather than just using the dist files.

**Comment by oholiab** [comment]
https://github.com/mmatuska/mfsbsd/blob/c04a0bafe67c7cbde6fe708d7b466fdd98621977/Makefile#L100 it looks like it's just taking the RELEASE of the host system when it's not specified and only using that as the name.

I'll verify here in a bit, I'm just modifying some of my build scripts and I'll do a fresh build.

**Comment by oholiab** [comment]
Hmm, I still appear to be ending up with a 10.2 mfsbsd when building from 10.2 and setting RELEASE to 10.3 :/

**Comment by vauxia** [comment]
I'm not sure if/how this is supposed to work.

I built mfsbsd using:

make tar BASE='../dist' PKG_STATIC='/usr/local/sbin/pkg-static' RELEASE=10.3-RELEASE. This did, in fact, create an mfsbsd-10.3-RELEASE-amd64.tar image.

However, when I booted and ran bsdinstall, I got systctl errors; "unknown pid vfs.zfs.min_auto_shift," and attempts to run e.g. zfsinstall result in a message that states "zfs.ko depends on kernel - not available or version mismatch".

And, yeah, output of 'uname -a' cites 10.2-RELEASE.

I'm not crafty enough with mfsbsd to get this running, so I'll probably just re-image the droplet, use these instructions for 10.2, and then freebsd-upgrade my way to victory.

It'll work for now, but I'm hoping for a better solution...

**Comment by 2bithacker** [comment]
@vauxia I ran into that problem the other day when I was running through this again. Before extracting the mfsbsd tar file over the root file system, do a `rm -rf /boot` as root. That'll clear out the 10.2 kernel and it's modules, which are then replaced with the 10.3 kernel and modules from the mfsbsd tar file.

**Comment by vauxia** [comment]
Thank you for the update! I did the 10.2 -> freebsd-update thing, but I'm happy there's a different workaround. I hope that DO supports both zfs and 10.3 soon!

**Comment by 2bithacker** [comment]
Added the rm -rf /boot to the instructions in 7ab13636d33aa0cf8cd889ce1eac3d8a420d7607.
